/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.demo.formularios.vistas;

import com.example.demo.capanegocio.LibroService;
import com.example.demo.capanegocio.PrestamoService;
import com.example.demo.capanegocio.UserService;
import com.example.demo.capanegocio.modelo.Libro;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author 03_06_2023
 */

@Component
@Scope("prototype")
public class CrearPrestamo extends javax.swing.JFrame {

    private long idUsuario;
    
    @Autowired
    private ApplicationContext context;
    
    @Autowired
    private PrestamoService prestamoService;
    
    @Autowired
    private UserService userService;
    
    @Autowired
    private LibroService libroService;
    
    /*@Autowired
    private MenuPrestamo prestamo;*/
    

    
    /**
     * Creates new form CrearPrestamo
     */
    public CrearPrestamo() {
        initComponents();
        initAdditionalComponents();
        cargarSugerencias(); 
    }
    
    private void cargarSugerencias() {
    // Obtener libros sugeridos
    ArrayList<Libro> librosSugeridos = libroService.recuperaLibros();
    
    // Crear modelo de tabla
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTableSugerencias.getModel();
    model.setRowCount(0); // Limpiar tabla
    
    // Llenar tabla con datos
    for (Libro libro : librosSugeridos) {
        model.addRow(new Object[]{
            libro.getIdLibro(),
            libro.getTitulo(),
            libro.getAutor() != null ? libro.getAutor().getNombre() : "Desconocido",
            "Disponible" 
        });
    }
}

    public void pasarid(long id){
       this.idUsuario = id; 
  }
    
    private void initAdditionalComponents() {
    // Crear el JScrollPane y JTable
    jScrollPaneSugerencias = new javax.swing.JScrollPane();
    jTableSugerencias = new javax.swing.JTable();
    
    // Configurar la tabla de sugerencias
    jTableSugerencias.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {"ID", "Título", "Autor", "Disponibles"}
    ));
    jScrollPaneSugerencias.setViewportView(jTableSugerencias);
    
    // Agregar el JScrollPane al JFrame manualmente
    getContentPane().add(jScrollPaneSugerencias, java.awt.BorderLayout.CENTER);
    
    // Listener para selección de libros
    jTableSugerencias.getSelectionModel().addListSelectionListener(event -> {
        if (!event.getValueIsAdjusting()) {
            int row = jTableSugerencias.getSelectedRow();
            if (row >= 0) {
                String idLibro = jTableSugerencias.getValueAt(row, 0).toString();
                jTextFieldIDLibro.setText(idLibro);
            }
        }
    });
    
    // Listener para doble clic 
    jTableSugerencias.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getClickCount() == 2) { // Verifica doble clic
                int row = jTableSugerencias.rowAtPoint(evt.getPoint());
                if (row >= 0) { // Asegura que se hizo clic en una fila válida
                    String idLibro = jTableSugerencias.getValueAt(row, 0).toString();
                    jTextFieldIDLibro.setText(idLibro);
                    
                    // Opcional: Poner foco en el campo de sucursal después de seleccionar
                    jTextFieldNombreSucursal.requestFocusInWindow();
                }
            }
        }
    });
    
    // Ajustar el layout existente
    pack();
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIDLibro = new javax.swing.JTextField();
        jTextFieldNombreSucursal = new javax.swing.JTextField();
        jButtonSolicitar = new javax.swing.JButton();
        jButtonIrMenuPrestamo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPaneSugerencias = new javax.swing.JScrollPane();
        jTableSugerencias = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Solicitar un prestamo");

        jLabel2.setText("ID libro");

        jLabel3.setText("Nombre de la sucursal");

        jTextFieldIDLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDLibroActionPerformed(evt);
            }
        });

        jButtonSolicitar.setText("Solicitar");
        jButtonSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolicitarActionPerformed(evt);
            }
        });

        jButtonIrMenuPrestamo.setText("Volver");
        jButtonIrMenuPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrMenuPrestamoActionPerformed(evt);
            }
        });

        jLabel4.setText("Sugerencias");

        jTableSugerencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneSugerencias.setViewportView(jTableSugerencias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldIDLibro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(jButtonIrMenuPrestamo)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jButtonSolicitar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldNombreSucursal))))
                            .addComponent(jLabel4))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneSugerencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonIrMenuPrestamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIDLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNombreSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSolicitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneSugerencias, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDLibroActionPerformed

    private void jButtonSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolicitarActionPerformed
        
        
        /*prestamoService.creaPrestamo(idLibro, idUsuario, nombreSucursal);
        JOptionPane.showMessageDialog(this, "Prestamo generado");
        */
        try{
            int idLibro=Integer.parseInt(jTextFieldIDLibro.getText());
            String nombreSucursal=jTextFieldNombreSucursal.getText();
            MenuPrestamo menuPrestamo=context.getBean(MenuPrestamo.class);
            prestamoService.creaPrestamo(idLibro, idUsuario, nombreSucursal);
            JOptionPane.showMessageDialog(this, "Prestamo generado");
            jTextFieldIDLibro.setText("");
            jTextFieldNombreSucursal.setText("");
            menuPrestamo.pasarId(idUsuario);
            menuPrestamo.setVisible(true);
            this.dispose();
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, "El libro no existe","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSolicitarActionPerformed

    private void jButtonIrMenuPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrMenuPrestamoActionPerformed
        MenuPrestamo menuPrestamo=context.getBean(MenuPrestamo.class);
        menuPrestamo.pasarId(idUsuario);
        menuPrestamo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonIrMenuPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIrMenuPrestamo;
    private javax.swing.JButton jButtonSolicitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPaneSugerencias;
    private javax.swing.JTable jTableSugerencias;
    private javax.swing.JTextField jTextFieldIDLibro;
    private javax.swing.JTextField jTextFieldNombreSucursal;
    // End of variables declaration//GEN-END:variables
}
