/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.demo.formularios.vistas;

import com.example.demo.capanegocio.CorreoService;
import com.example.demo.capanegocio.LibroService;
import com.example.demo.capanegocio.PrestamoService;
import com.example.demo.capanegocio.UserService;
import com.example.demo.capanegocio.modelo.Libro;
import com.example.demo.capanegocio.modelo.Prestamo;
import com.example.demo.capanegocio.modelo.Usuario;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author 03_06_2023
 */

@Component
@Scope("prototype")
public class CrearPrestamo extends javax.swing.JFrame {

    private long idUsuario;
    
    @Autowired
    private ApplicationContext context;
    
    @Autowired
    private PrestamoService prestamoService;
    
    @Autowired
    private UserService userService;
    
    @Autowired
    private CorreoService correoService;
    
    @Autowired
    private LibroService libroService;
    
    /*@Autowired
    private MenuPrestamo prestamo;*/
    

    
    /**
     * Creates new form CrearPrestamo
     */
    public CrearPrestamo() {
        initComponents();

    }
    
   

    public void pasarid(long id){
       this.idUsuario = id; 
  }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIDLibro = new javax.swing.JTextField();
        jButtonSolicitar = new javax.swing.JButton();
        jButtonIrMenuPrestamo = new javax.swing.JButton();
        jComboBoxSucursales = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Solicitar un prestamo");

        jLabel2.setText("ID libro");

        jLabel3.setText("Nombre de la sucursal");

        jTextFieldIDLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDLibroActionPerformed(evt);
            }
        });

        jButtonSolicitar.setText("Solicitar");
        jButtonSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolicitarActionPerformed(evt);
            }
        });

        jButtonIrMenuPrestamo.setText("Volver");
        jButtonIrMenuPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrMenuPrestamoActionPerformed(evt);
            }
        });

        jComboBoxSucursales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zocalo", "Santa Fe", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldIDLibro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jButtonIrMenuPrestamo)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSolicitar)
                            .addComponent(jComboBoxSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonIrMenuPrestamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIDLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSolicitar)
                .addGap(248, 248, 248))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDLibroActionPerformed

    private void jButtonSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolicitarActionPerformed
        
        
        /*prestamoService.creaPrestamo(idLibro, idUsuario, nombreSucursal);
        JOptionPane.showMessageDialog(this, "Prestamo generado");
        */
        try{
            int idLibro=Integer.parseInt(jTextFieldIDLibro.getText());
            String nombreSucursal=jComboBoxSucursales.getSelectedItem().toString();
            MenuPrestamo menuPrestamo=context.getBean(MenuPrestamo.class);
            
            //prestamoService.creaPrestamo(idLibro, idUsuario, nombreSucursal);
            Prestamo prestamo = prestamoService.creaPrestamo(idLibro, idUsuario, nombreSucursal);
            
            String tituloLibro = prestamo.getLibro().getTitulo();
            LocalDate fechaSolicitud = prestamo.getFechaPrestamo();
            LocalDate fechaDevolucion = prestamo.getFechaLimite();
            
            Usuario usuario = userService.obtenerUsuarioPorId(idUsuario);
            
            String subject = "Confirmación de préstamo de libro";
            String content = String.format(
                    "Tu solicitud de préstamo ha sido registrada con éxito:\n\n" +
                    "ID del libro: %d\nTítulo: %s\nFecha de solicitud: %s\nFecha de devolución: %s\n\n" +
                    "¡Gracias por su visita!",
                    idLibro, tituloLibro, fechaSolicitud, fechaDevolucion
            );
            
            correoService.sendCorreo(usuario.getCorreo(), subject, content, null);
            
            // Solo si todo lo anterior funcionó:
            JOptionPane.showMessageDialog(this, "Préstamo generado y correo de confirmación enviado.");
               
            jTextFieldIDLibro.setText("");
            
            
            menuPrestamo.pasarId(idUsuario);
            menuPrestamo.setVisible(true);
            this.dispose();
            
            
            
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, "El libro no existe","Error",JOptionPane.ERROR_MESSAGE);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error al procesar la solicitud :c", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        
        }
    }//GEN-LAST:event_jButtonSolicitarActionPerformed

    private void jButtonIrMenuPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrMenuPrestamoActionPerformed
        MenuPrestamo menuPrestamo=context.getBean(MenuPrestamo.class);
        menuPrestamo.pasarId(idUsuario);
        menuPrestamo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonIrMenuPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIrMenuPrestamo;
    private javax.swing.JButton jButtonSolicitar;
    private javax.swing.JComboBox<String> jComboBoxSucursales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldIDLibro;
    // End of variables declaration//GEN-END:variables
}
