/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package com.example.demo.formularios.vistas;


//import CapaNegocio.ManejadorLibros;
//import CapaPersistencia.ConexionDB;
import com.example.demo.capanegocio.PrestamoService;
import com.example.demo.capapersistencia.PrestamoRepository;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;


/**
 *
 * @author 03_06_2023
 */

@Component
@Scope("prototype")
public class FormularioDevolucion extends javax.swing.JFrame {
    
    @Autowired
    private PrestamoService prestamoService;
    
    @Autowired
    private ApplicationContext context;
    
    /*@Autowired
    private MenuUsuario usuario;*/
    

    /**
     * Creates new form FormularioDevolucion
     */
    
    @Autowired 
    private MenuUsuario menuUsuario;
    public FormularioDevolucion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private long idUsuario; 
    
    public void  pasarId(long id){
       this.idUsuario = id; 
  }
 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDLibro = new javax.swing.JTextField();
        jButtonDevolver = new javax.swing.JButton();
        jButtonIrAMenuUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Devoluciones");

        jLabel2.setText("ID prestamo");

        txtIDLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDLibroActionPerformed(evt);
            }
        });

        jButtonDevolver.setText("Devolver");
        jButtonDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolverActionPerformed(evt);
            }
        });

        jButtonIrAMenuUsuario.setText("Volver");
        jButtonIrAMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrAMenuUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtIDLibro)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButtonDevolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButtonIrAMenuUsuario)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonIrAMenuUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIDLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonDevolver)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDLibroActionPerformed
        txtIDLibro.setText("");
    }//GEN-LAST:event_txtIDLibroActionPerformed

    private void jButtonDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolverActionPerformed
        String numero=txtIDLibro.getText();
        
        
         try {
            int idPrestamo = Integer.parseInt(numero);
            prestamoService.registrarDevolucion(idPrestamo, idUsuario);
            JOptionPane.showMessageDialog(this, "Devolucion exitosa");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID de libro válido.","Error",JOptionPane.ERROR_MESSAGE);
 
        }catch (IllegalArgumentException a){
            JOptionPane.showMessageDialog(this, a.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
        /*
        String sqlSelect = "SELECT id_libro, id_usuario FROM Prestamo WHERE id_prestamo = ?";

        //Connection conexion = new ConexionDB().obtenerConexion();

        int idPrestamoInt;

        try {
            idPrestamoInt = Integer.parseInt(idPrestamo);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID de libro válido.");
            return;
        }

        try{
            PreparedStatement pstSelect = conexion.prepareStatement(sqlSelect);
            pstSelect.setInt(1, idPrestamoInt);
            ResultSet rs = pstSelect.executeQuery();

            if (rs.next()) {
                int idLibro = rs.getInt("id_libro");
                int idUsuario = rs.getInt("id_usuario");

                //ManejadorLibros manejador=new ManejadorLibros();

                JOptionPane.showMessageDialog(this, manejador.registrarDevolucion(idPrestamoInt, idUsuario, idLibro));
            }else{
                JOptionPane.showMessageDialog(this, "No se encontró el libro");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error");
        }

        txtIDLibro.setText("");*/
    }//GEN-LAST:event_jButtonDevolverActionPerformed

    private void jButtonIrAMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrAMenuUsuarioActionPerformed
        MenuUsuario menuUsuario=context.getBean(MenuUsuario.class);
        menuUsuario.pasarId(idUsuario);
        menuUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonIrAMenuUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormularioDevolucion().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDevolver;
    private javax.swing.JButton jButtonIrAMenuUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtIDLibro;
    // End of variables declaration//GEN-END:variables
}
