/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.demo.formularios.vistas;

import com.example.demo.capanegocio.ItemInventarioService;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author 03_06_2023
 */
@Component
@Scope("prototype")
public class HorarioSucursales extends javax.swing.JFrame {

    /**
     * Creates new form HorarioSucursales
     */
    
    @Autowired
    private ItemInventarioService itemInventarioService;
    
    @Autowired
    private ApplicationContext context;
    
    private long idUsuario;
    
    public HorarioSucursales() {
        initComponents();
    }

    //El metodo pasarId se encarga de que la clase pase el id a otras
    //con el fin de que el sistema persista
    public void  pasarId(long id){
       this.idUsuario = id; 
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxSucursales = new javax.swing.JComboBox<>();
        jButtonBuscarSucursal = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIDLibro = new javax.swing.JTextField();
        jButtonBuscarIDLibro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Horario de otras sucursales");

        jLabel2.setText("Selecciona una sucursal");

        jComboBoxSucursales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zocalo", "Santa Fe", " ", " " }));
        jComboBoxSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSucursalesActionPerformed(evt);
            }
        });

        jButtonBuscarSucursal.setText("Buscar");
        jButtonBuscarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarSucursalActionPerformed(evt);
            }
        });

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Libro");

        jButtonBuscarIDLibro.setText("Buscar");
        jButtonBuscarIDLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarIDLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButtonVolver)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIDLibro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscarSucursal)
                    .addComponent(jButtonBuscarIDLibro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVolver)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldIDLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscarIDLibro))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jButtonBuscarSucursal))
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//En este metodo se muestran las sucursales
    private void jButtonBuscarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarSucursalActionPerformed
        String opcion=jComboBoxSucursales.getSelectedItem().toString();
        //De acuerdo a lo seleccionado en el combobox se mostrara un mensaje u otro, con la 
        //direccion de la sucursal elegida
        if(opcion.equals("Zocalo")){
            JOptionPane.showMessageDialog(this,"Direccion: San Salvador #12 Colonia Centro\n"
                    + "Horario: Lunes a viernes: 8:00 a 19:00");
        }else if(opcion.equals("Santa Fe")){
            JOptionPane.showMessageDialog(this,"Direccion: Tlalpan 14\n"
                    + "Horario: Lunes a viernes: 8:00 a 19:00");
        }
    }//GEN-LAST:event_jButtonBuscarSucursalActionPerformed

    private void jComboBoxSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSucursalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSucursalesActionPerformed
    //Con este metodo volvemos a la clase MenuUsuario
    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        MenuUsuario usuario=context.getBean(MenuUsuario.class);
        usuario.pasarId(idUsuario);
        usuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed
    //En este metodo se busca el libro correspondiente al id ingresado
    private void jButtonBuscarIDLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarIDLibroActionPerformed
        //Este try-catch captura los siguientes casos:
        //1-El usuario ingresa un id invalido (por ejemplo letras o deja el espacio en blanco
        //2-El id ingresado no corresponde a un libro en la base de datos
        try{
            int idLibro=Integer.parseInt(jTextFieldIDLibro.getText());
            JOptionPane.showMessageDialog(this, itemInventarioService.recuperaInventarioPorIdLibro(idLibro));
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "ID invalido","Error",JOptionPane.ERROR_MESSAGE);
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(this, "Libro no encontrado","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonBuscarIDLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HorarioSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HorarioSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HorarioSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HorarioSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HorarioSucursales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarIDLibro;
    private javax.swing.JButton jButtonBuscarSucursal;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxSucursales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldIDLibro;
    // End of variables declaration//GEN-END:variables
}
