/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.demo.formularios.admin;

import com.example.demo.capanegocio.LibroService;
import com.example.demo.capapersistencia.LibroRepository;
import com.example.demo.capanegocio.modelo.Autor;
import com.example.demo.capapersistencia.AutorRepository;

import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import com.example.demo.capanegocio.CorreoService;
import com.example.demo.capanegocio.InventarioService;
import com.example.demo.capanegocio.SucursalSevice;
import com.example.demo.capanegocio.UserService;
import com.example.demo.capanegocio.ItemInventarioService;
import com.example.demo.capanegocio.modelo.Inventario;
import com.example.demo.capanegocio.modelo.Libro;
import com.example.demo.capanegocio.modelo.Sucursal;
import com.example.demo.capanegocio.modelo.Usuario;
import com.example.demo.capapersistencia.InventarioRepository;
import jakarta.annotation.PostConstruct;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.text.NumberFormatter;
import java.text.NumberFormat;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Diegogó
 */

@Component
@Scope("prototype")
public class FormularioLibros extends javax.swing.JFrame {
    
    private List<Usuario> usuarios;
    
    @Autowired
    LibroService libroService;
    
    @Autowired
    AutorRepository autorRepository;
    
    @Autowired
    LibroRepository libroRepository;
    
    @Autowired
    InventarioRepository inventarioRepository;
    
    @Autowired
    private ApplicationContext context;
    
    @Autowired
    private CorreoService correoService;
    
    @Autowired
    private UserService userService;
    
    @Autowired
    private SucursalSevice sucursalSevice;
    
    @Autowired
    private InventarioService inventarioService;
    
    @Autowired
    private ItemInventarioService itemInventarioService;
    
    
    @Autowired
    public FormularioLibros() {
        initComponents();
    }
    
    @PostConstruct
    private void cargarSucursales(){
        List<Sucursal> sucursales = sucursalSevice.obtenerSucursales();
        DefaultComboBoxModel<String> modelo =new DefaultComboBoxModel<>();
        for(Sucursal s : sucursales){
            modelo.addElement(s.getNombre());
        }
        cmbSucursal.setModel(modelo);
    }
    
    /*@PostConstruct
    private void initCustomComponents(){
        NumberFormat format=NumberFormat.getIntegerInstance();
        NumberFormatter formatter=new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setAllowsInvalid(false);
        formatter.setCommitsOnValidEdit(true);
        ((javax.swing.JFormattedTextField) txtIdAutor).setFormatterFactory(
        new javax.swing.text.DefaultFormatterFactory(formatter));
        cargarSucursales();
    }*/
    
    private void notificarUsuariosNuevoLibro(String tituloLibro){
        List<Usuario> usuarios = userService.recuperaUsuarios();

        String subject = "Nuevo libro disponible: " + tituloLibro;
        String content = "Estimado usuario,\n\n"

                   + "Nos complace informarte que se ha agregado un nuevo libro a la biblioteca: " + tituloLibro + ".\n"
                   + "¡Visita nuestro portal para más detalles!\n\n"
                   + "Saludos,\nBiblioteca Guam";
    


        for(Usuario usuario : usuarios) {
            try {
                correoService.sendCorreo(usuario.getCorreo(), subject, content, null);
            } catch (Exception e) {
            // Manejar errores individualmente, por ejemplo, loguear el error
                JOptionPane.showMessageDialog(this, "Error al enviar correo a "+usuario.getCorreo(),"Error", JOptionPane.ERROR_MESSAGE);
                System.err.println("Error al enviar correo a " + usuario.getCorreo() + ": " + e.getMessage());
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtEdicion = new javax.swing.JTextField();
        cmbSucursal = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtIdAutor = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Titulo");

        jLabel2.setText("Editorial");

        jLabel3.setText("Cantidad");

        jLabel4.setText("Edición");

        jLabel5.setText("Autor");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        jLabel6.setText("Agregar Libros");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        cmbSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSucursalActionPerformed(evt);
            }
        });

        jLabel7.setText("Sucursal");

        txtIdAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Guardar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(80, 80, 80)
                                .addComponent(Volver))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSucursal, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEdicion)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(txtEditorial, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdAutor))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volver)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(Guardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtEditorialActionPerformed(java.awt.event.ActionEvent evt){
        txtTitulo.setText("");
    }
    
    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt){
        txtTitulo.setText("");
    }
    
    private void txtEdicionActionPerformed(java.awt.event.ActionEvent evt){
        txtTitulo.setText("");
    }
    
    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt){
        txtTitulo.setText("");
    }
    
    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        MenuAdmin mAd = context.getBean(MenuAdmin.class);
        mAd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        
        
        
        try{
            String titulo=txtTitulo.getText();
            String editorial=txtEditorial.getText();
            int cantidad = Integer.parseInt(txtCantidad.getText());
            int anio = Integer.parseInt(txtEdicion.getText());
            long idAutor = Long.parseLong(txtIdAutor.getText());
            String nombreSuc = (String) cmbSucursal.getSelectedItem();
            Autor autorExistente = autorRepository.findById(idAutor)
                    .orElseThrow(()-> new IllegalArgumentException("Autor no encontrado: " + idAutor));
            
            //libroService.agregaLibro(titulo, editorial, anio, idAutor);
            Libro libro =libroService.agregaLibro(titulo, editorial, anio, idAutor);
            Sucursal sucursal=sucursalSevice.recuperaSucursalPorNombre(nombreSuc);
            Inventario inventario =inventarioService.recuperarInventarioPorSucursal(sucursal);
            
            itemInventarioService.agregarLibro(libro.getIdLibro(), inventario.getIdInventario(), cantidad);
            
            JOptionPane.showMessageDialog(this, "Libro guardado exitosamente");
            notificarUsuariosNuevoLibro(titulo);
            MenuAdmin mAd=context.getBean(MenuAdmin.class);
            mAd.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al introducir datos.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            
}
    }//GEN-LAST:event_GuardarActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void cmbSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSucursalActionPerformed

    private void txtIdAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Volver;
    private javax.swing.JComboBox<String> cmbSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JFormattedTextField txtIdAutor;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
